### ISSUE TITLE
getting error no matter how i try to import the assets, tried cloning and zip

### ISSUE THREAD

**Issue by egoolsen** [reedbarger/react-slack-clone#6]
npm i      
npm ERR! code 1
npm ERR! path /home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc
npm ERR! command failed
npm ERR! command sh -c ./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! make: Entering directory '/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/build'
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
npm ERR! make: Entering directory '/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/build'
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
npm ERR! make: Leaving directory '/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/build'
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
npm ERR! Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=7 --node_abi_napi=napi' (1)
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_trace.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz_registry.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_factory.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/status_util.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_internal.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/message_compress.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_gzip.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_identity.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/format_request.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/httpcli.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/parser.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/call_combiner.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/combiner.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_posix.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_uv.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_windows.o
npm ERR!   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o
npm ERR! make: Leaving directory '/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/build'
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.10.3
npm ERR! node-pre-gyp info using node@12.21.0 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" (not found)
npm ERR! node-pre-gyp http GET https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.1/node-v72-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp http 403 https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.1/node-v72-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.1/node-v72-linux-x64-glibc.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for grpc@1.13.1 and node@12.21.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.1/node-v72-linux-x64-glibc.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for grpc@1.13.1 and node@12.21.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.21.0 | linux | x64
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.21.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.21.0 | linux | x64
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.21.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp gyp info spawn /usr/bin/python3
npm ERR! infogyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/egon/.cache/node-gyp/12.21.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/egon/.cache/node-gyp/12.21.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/egon/.cache/node-gyp/12.21.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR!  spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/egon/.cache/node-gyp/12.21.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/egon/.cache/node-gyp/12.21.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/egon/.cache/node-gyp/12.21.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.21.0 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.21.0 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! sed: can't read ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
npm ERR! rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
npm ERR! make: *** [grpc.target.mk:458: Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.10.0-kali4-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc" "--napi_version=7" "--node_abi_napi=napi"
npm ERR! gyp ERR! cwd /home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc
npm ERR! gyp ERR! node -v v12.21.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=7 --node_abi_napi=napi' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm ERR! node-pre-gyp ERR! System Linux 5.10.0-kali4-amd64
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
npm ERR! node-pre-gyp ERR! cwd /home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc
npm ERR! node-pre-gyp ERR! node -v v12.21.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.10.3
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! ../deps/grpc/src/core/lib/iomgr/error.cc: In function ‘void internal_set_time(grpc_error**, grpc_error_times, gpr_timespec)’:
npm ERR! ../deps/grpc/src/core/lib/iomgr/error.cc:276:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
npm ERR!   276 |   memcpy((*err)->arena + slot, &value, sizeof(value));
npm ERR!       |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! In file included from ../deps/grpc/src/core/lib/iomgr/error.cc:36:
npm ERR! ../deps/grpc/src/core/lib/iomgr/error_internal.h:58:12: note: at offset 0 to object ‘grpc_error::arena’ with size 0 declared here
npm ERR!    58 |   intptr_t arena[0];
npm ERR!       |            ^~~~~
npm ERR! In function ‘void internal_add_error(grpc_error**, grpc_error*)’,
npm ERR!     inlined from ‘grpc_error* grpc_error_create(const char*, int, grpc_slice, grpc_error**, size_t)’ at ../deps/grpc/src/core/lib/iomgr/error.cc:350:23:
npm ERR! ../deps/grpc/src/core/lib/iomgr/error.cc:299:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
npm ERR!   299 |   memcpy((*err)->arena + slot, &new_last, sizeof(grpc_linked_error));
npm ERR!       |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! In function ‘void internal_add_error(grpc_error**, grpc_error*)’,
npm ERR!     inlined from ‘grpc_error* grpc_error_add_child(grpc_error*, grpc_error*)’ at ../deps/grpc/src/core/lib/iomgr/error.cc:505:21:
npm ERR! ../deps/grpc/src/core/lib/iomgr/error.cc:299:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
npm ERR!   299 |   memcpy((*err)->arena + slot, &new_last, sizeof(grpc_linked_error));
npm ERR!       |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! cc1plus: all warnings being treated as errors
npm ERR! make: *** [grpc.target.mk:458: Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.10.0-kali4-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc" "--napi_version=7" "--node_abi_napi=napi"
npm ERR! gyp ERR! cwd /home/egon/Development/ReactTutorial/ReactChatProject/react-slack-clone/node_modules/grpc
npm ERR! gyp ERR! node -v v12.21.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/egon/.npm/_logs/2021-03-12T23_37_52_214Z-debug.log

**Comment by bluVshal** [comment]
Hello,
            Have you tried downgrading node and npm?
